# Generated by Django 3.0.7 on 2020-06-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfarim_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
    atomic = False